export const PASSWORD_INPUT_TEST_ID = `PASSWORD_INPUT_TEST_ID`;
export const PASSWORD_INPUT_ICON_BUTTON_TEST_ID = `PASSWORD_INPUT_ICON_BUTTON_TEST_ID`;
export const PASSWORD_INPUT_OPEN_EYE_TEST_ID = `PASSWORD_INPUT_OPEN_EYE_TEST_ID`;
export const PASSWORD_INPUT_CLOSED_EYE_TEST_ID = `PASSWORD_INPUT_CLOSED_EYE_TEST_ID`;
